### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by JKChen** [thedevdojo/voyager-polls#6]
- PHP:                    7.1.6
- Laravel:                5.4.*
- Voyager:              ^0.11.14
- Voyager-hooks:   ^1.0

![why](https://user-images.githubusercontent.com/7858123/30155687-0c1040cc-93f0-11e7-98fc-406657d807bf.png)

Need u help?

**Comment by marktopper** [comment]
I guess you have upgraded from Voyager v0.11.
Fix this easily by running `php artisan hook:setup`.

EDIT: Will update the Voyager upgrade guide.
